version: 2
jobs:
  job1:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            sudo apt-get update
            echo "Doing some cool stuff"
            echo "displaying directories"
            ls -la
            echo "creating a file that won't persist" >> file.txt
            echo "displaying working context"
            echo $coolVar
  thisCouldBeAnyName:
    machine: true
    working_directory: ~/coolFolder
    steps:
      - run:
          name: displaying things
          command: |
            echo "displaying files in home folder"
            ls -la
            pwd
      - run:
          name: creating a file that will persist
          command: |
            sha=$CIRCLE_SHA1
            TAG=${sha:0:7}
            echo "image tag:" $TAG >> tag.txt
      - run:
          name: print working dir
          command: |
            pwd
            ls -la
      - persist_to_workspace:
          root: ~/coolFolder
          paths:
            - .
  showingFiles:
    machine: true
    working_directory: ~/coolFolder
    steps:
      - attach_workspace:
          at: ~/coolFolder
      - run:
          name: displaying files
          command: |
            ls -la
            echo "displaying working context"
            echo $coolVar
  showingFiles:
    machine: true
    working_directory: ~/myJobFolder
    steps:
      - run:
          name: this will trigger only with myBranch
          command: |
            ls -la
            echo "displaying working context"
            echo $coolVar            
workflows:
  version: 2
  Cool-WorkFlow:
    jobs:
      - job1
      - thisCouldBeAnyName:
          requires:
            - job1
          filters:
            branches:
              only: master
          context: dev
      - hold:
          type: approval
          filters:
            branches:
              only: master
      - showingFiles:
          requires:
            - thisCouldBeAnyName
            - hold
          filters:
            branches:
              only: master
          context: prod

  Other-Cool-Flow:
    jobs:
      - youHad-1-job:
          filters:
            branches:
              only: myBranch
          context: dev
